# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turing.ui'
#
# Created: Fri Jun  9 22:01:42 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Turing(object):
    def setupUi(self, Turing):
        Turing.setObjectName("Turing")
        Turing.resize(448, 632)
        self.centralWidget = QtGui.QWidget(Turing)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        font.setItalic(True)
        font.setUnderline(True)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.Panel)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setLineWidth(3)
        self.label.setMidLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 401, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(7, 150, 411, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 80, 411, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.n_trs = QtGui.QLineEdit(self.centralWidget)
        self.n_trs.setGeometry(QtCore.QRect(20, 170, 41, 23))
        self.n_trs.setObjectName("n_trs")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 201, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.I_trs = QtGui.QPushButton(self.centralWidget)
        self.I_trs.setGeometry(QtCore.QRect(280, 170, 94, 24))
        self.I_trs.setObjectName("I_trs")
        self.box = QtGui.QGroupBox(self.centralWidget)
        self.box.setEnabled(True)
        self.box.setGeometry(QtCore.QRect(10, 210, 421, 371))
        self.box.setObjectName("box")
        self.list_0 = QtGui.QTableView(self.box)
        self.list_0.setGeometry(QtCore.QRect(10, 140, 256, 192))
        self.list_0.setObjectName("list_0")
        self.bt1 = QtGui.QPushButton(self.box)
        self.bt1.setGeometry(QtCore.QRect(280, 140, 121, 31))
        self.bt1.setObjectName("bt1")
        self.in1 = QtGui.QLineEdit(self.box)
        self.in1.setEnabled(True)
        self.in1.setGeometry(QtCore.QRect(10, 90, 251, 23))
        self.in1.setObjectName("in1")
        self.bt3 = QtGui.QPushButton(self.box)
        self.bt3.setGeometry(QtCore.QRect(280, 220, 121, 31))
        self.bt3.setObjectName("bt3")
        self.label_4 = QtGui.QLabel(self.box)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 401, 81))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtGui.QLabel(self.box)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_6.setObjectName("label_6")
        self.bt2 = QtGui.QPushButton(self.box)
        self.bt2.setGeometry(QtCore.QRect(280, 180, 121, 31))
        self.bt2.setObjectName("bt2")
        Turing.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(Turing)
        self.mainToolBar.setObjectName("mainToolBar")
        Turing.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(Turing)
        self.statusBar.setObjectName("statusBar")
        Turing.setStatusBar(self.statusBar)

        self.retranslateUi(Turing)
        QtCore.QMetaObject.connectSlotsByName(Turing)

    def retranslateUi(self, Turing):
        Turing.setWindowTitle(QtGui.QApplication.translate("Turing", "Maquina de Turing", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Turing", "Simulador Máquina de Turing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Turing", "Objetivo: Este simulador, tiene como finalidad probar la secuencia de trancisiones de una MT con una cierta palabra, donde el resultado esperado debe ser aceptado o rechazado sea el caso.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Turing", "Ingrese el Numero de Transiciones a simular", None, QtGui.QApplication.UnicodeUTF8))
        self.I_trs.setText(QtGui.QApplication.translate("Turing", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.box.setTitle(QtGui.QApplication.translate("Turing", "Transiciones a simular", None, QtGui.QApplication.UnicodeUTF8))
        self.bt1.setText(QtGui.QApplication.translate("Turing", "Agrega", None, QtGui.QApplication.UnicodeUTF8))
        self.bt3.setText(QtGui.QApplication.translate("Turing", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Turing", "Ingrese transiciones del tipo: \"estado_actual,simbolo_actual_del_cabezal,estado_siguiente,simbolo_a_escribir,direccion_de_avance separar transiciones con \';\' y direccion de avance \'I\' o \'D\' \"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Turing", "Listado de transiciones", None, QtGui.QApplication.UnicodeUTF8))
        self.bt2.setText(QtGui.QApplication.translate("Turing", "Editar", None, QtGui.QApplication.UnicodeUTF8))

